config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  
  resource :about, only: [:show], controller: 'about'

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  delete 'logout', to: 'sessions#destroy', as: :logout

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  http_basic_authenticate_with name: "Jungle", password: "book"

  def show
    @product_count = Product.count
    @category_count = Category.count
  end

end

app/views/admin/dashboard/show.html.erb
<div class="container">
  <h2 class="my-3">Admin Dashboard</h2>

  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Total Products</h3>
          <p class="display-4">
            <%= link_to @product_count, admin_products_url %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Total Categories</h3>
          <p class="display-4">
            <%= link_to @category_count, admin_categories_url %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>